### ISSUE TITLE
key/2 function

### ISSUE THREAD

**Issue by lpil** [AVUIs/cantor-dust#7]
Perhaps it's because I'm 2 bottles of rose wine into my birthday, but I can't immediately see where this `key/2` function comes from.

https://github.com/AVUIs/cantor-dust/blob/fe72c4b24e0968b254489a1f6cb73e344b6a4d90/app/controllers/keyboard.js#L14

Is it in the global scope? If so, can we import it like a regular function in order to make module dependencies easier to reason about?

**Comment by berkan** [comment]
happy belated birthday mr pilfold! hope you had a good one, i shall
remember to buy you a drink when we next meet (rose, clear, pale -- you
specify the colour/shade of the drink :)

that function comes from vendor/keymaster.js -- because the keyboard
interface works a lot with modifier keys, i thought i'd use something that
has been tested before. it may have a dont-pollute-global-namespace switch,
but i didn't check tbh.

**Comment by lpil** [comment]
<3
